name: task_machine_flutter
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.16.0-85.0.dev <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  task_machine:
    git: 
      url: https://github.com/cedvdb/client_task_machine.git
      branch: io

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

